### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by umranyaman** [sid-sethi/ANNSeq#3]
Hello,

I am trying the pipeline with the ONT long-read data. I have got the error below I could not sort that out what to write on the sample, or what should correspond to it. I thought the error occurred due to the sample input.

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 5
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/snakemake/__init__.py", line 699, in snakemake
    success = workflow.execute(
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/snakemake/workflow.py", line 1056, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/snakemake/dag.py", line 2192, in stats
    yield tabulate(rows, headers="keys")
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/Users/umranyaman/opt/anaconda3/envs/annseq/lib/python3.10/site-packages/snakemake/rules.py", line 1127, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'

My config.yml is attached as pdf.

Thanks very much,
Umran
[config.pdf](https://github.com/sid-sethi/ANNSeq/files/9810331/config.pdf)

**Comment by sid-sethi** [comment]
Hi Umran,

Seems like there was a bug with the version of snakemake I had in the environment file, on which I did not test the pipeline. I have now updated the environment file to an earlier version of snakemake. Could you please update the conda environment (or make a new one from scratch) and try again?

You can download the updated `environment.yml` file and run this command to update the conda env: `conda env update -f environment.yml --name annseq --prune`.

Also, make sure your provide the fastq in the config file : "/Volumes/Elements/Dervis_amyloid_mice_batch1_26052021/
Pool1_12_2e_12_2j/20210526_1109_1-E9-H9_PAG24430_42eb0d50/fastq_pass/barcode01/xxxxx.fastq"

Regards,
Sid

**Comment by umranyaman** [comment]
Thanks very much Sid, 

I get the exit code 127, more details about the log below:

Building DAG of jobs...
Using shell: /bin/bash
Provided cluster nodes: 4
Job counts:
        count   jobs
        1       all
        1       minimap_mapping
        1       nanostat
        1       pychopper
        1       sort_sam
        1       talon_abundance
        1       talon_annotate
        1       talon_create_GTF
        1       talon_filter_transcripts
        1       talon_initialize_database
        1       talon_label_reads
        11
Select jobs to execute...

[Tue Oct 18 17:07:29 2022]
rule talon_initialize_database:
    input: /Users/umranyaman/Desktop/talon-deneme/gencode.vM21.annotation.gtf
    output: Talon/talon_gencode.vM21.annotation.db
    log: Talon/talon_db.log
    jobid: 3

Error submitting jobscript (exit code 127):


[Tue Oct 18 17:07:29 2022]
rule nanostat:
    input: /Volumes/Elements/Dervis_amyloid_mice_batch1_26052021/Pool1_12_2e_12_2j/20210526_1109_1-E9-H9_PAG24430_42eb0d50/pipeline-nanopore-ref-isoforms/processed_rea$
    output: Nanostat/stat_out.txt
    jobid: 1
    threads: 20

Error submitting jobscript (exit code 127):


[Tue Oct 18 17:07:29 2022]
rule pychopper:
    input: /Volumes/Elements/Dervis_amyloid_mice_batch1_26052021/Pool1_12_2e_12_2j/20210526_1109_1-E9-H9_PAG24430_42eb0d50/pipeline-nanopore-ref-isoforms/processed_rea$
    output: Pychopper/mouse_cortex_pychopped.fastq
    log: /Users/umranyaman/Desktop/talon/Pychopper/mouse_cortex_pychopped.log
    jobid: 9
    threads: 20

Error submitting jobscript (exit code 127):

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/umranyaman/Desktop/talon/ANNSeq/.snakemake/log/2022-10-18T170729.011827.snakemake.log

What do you think might be occurring? I have provided concatenated fastq files in the barcode01 directory, as an input fastq files.

Best,
Umran

**Comment by umranyaman** [comment]
Just forgot to add that I am initially running this pipeline locally, seems to be commands are not found although I run the pipeline on annseq environment.

**Comment by sid-sethi** [comment]
Can you please paste your snakemake command and config file? Also, please test if the tools are installed inside the annseq environment. For instance, try if this works: `talon -h`

**Comment by umranyaman** [comment]
Hi Sid! All the functions works fine in the environment. Not sure what the problem was. Once I rerun the pipeline it run without any issue actually. Thanks very much!

**Comment by sid-sethi** [comment]
Great, thanks Umran for letting me know!
