### ISSUE TITLE
TranscriptClean

### ISSUE THREAD

**Issue by umranyaman** [sid-sethi/ANNSeq#5]
Hi @sid-sethi,

I was wondering whether you have considered adding the TranscriptClean before the Talon step.  It is suggested but d like to get your opinion as well.

Best,
Umran

**Comment by sid-sethi** [comment]
Hi Umran,

Apologies for my late reply. When I tried TranscriptClean at the time of developing this pipeline, it used huge amounts of RAM and it was also quite a time consuming step. We had big datasets and I had to split the data by chromosomes to avoid breaking the server during TranscriptClean. These problems may have been fixed now in TranscriptClean, but at that time we decided not to use it as we were not primarily interested in variant calling. I hope this helps.

Regards,
Sid
